/**
 * Usernames that would collide with a real route (or are otherwise unsafe)
 * and therefore cannot be claimed by a host. Because host profiles now live
 * at the root (`/<username>`), any single-segment route name must be reserved
 * so a username never shadows — or gets shadowed by — a real page.
 *
 * Keep this in sync with the top-level folders in `src/app`.
 */
export const RESERVED_USERNAMES = new Set<string>([
  // Real top-level routes
  "about",
  "account",
  "admin",
  "api",
  "auth",
  "book",
  "bookings",
  "contact",
  "host",
  "hosts",
  "invite",
  "login",
  "messages",
  "packages",
  "passport",
  "plus",
  "privacy",
  "refunds",
  "report",
  "search",
  "signup",
  "stories",
  "terms",
  "trips",
  "trust",
  // Reserved for future use / safety
  "home",
  "index",
  "help",
  "support",
  "settings",
  "pricing",
  "blog",
  "news",
  "faq",
  "careers",
  "jobs",
  "press",
  "legal",
  "cookies",
  "security",
  "status",
  "explore",
  "community",
  "originals",
  "packuptrip",
  "new",
  "edit",
  "me",
  "my",
  "user",
  "users",
  "u",
  "profile",
  "profiles",
  "dashboard",
  "notifications",
  "inbox",
  "chat",
  "checkout",
  "pay",
  "payment",
  "payments",
  "www",
  "app",
  "mail",
  "static",
  "public",
  "assets",
  "images",
  "img",
  "favicon",
  "robots",
  "sitemap",
  "manifest",
  "null",
  "undefined",
  "true",
  "false",
]);

export function isReservedUsername(name: string): boolean {
  return RESERVED_USERNAMES.has(name.trim().toLowerCase());
}
